name = "how-to-answer-what-are-your-salary-expectations"
main = "worker/index.js"
compatibility_date = "2024-04-01"

[assets]
directory = "./dist"

[vars]
# Public vars go here
# Secrets like NINJA_API_KEY must be set via `wrangler secret put NINJA_API_KEY`
